### ISSUE TITLE
README.md 작성

### ISSUE THREAD

**Issue by greatSumini** [DEV-MUGLES/react-excel#5]
요구사항
1. 간단한 설명, Getting Started, Usage 등
2. 뱃지 추가해주세용

추가할만한 뱃지
1. npm 패키지 버전
2. 패키지 번들 사이즈
3. 라이센스
3. CI, CD success 여부
4. 테스트 커버리지
5. 깃헙 스타수?

**Comment by syoung125** [comment]
182d9db17fca47216eec8ce2c1a4221039405131

**Comment by greatSumini** [comment]
뱃지도 추가해주세요!

**Comment by syoung125** [comment]
5c994b9bcc4d6126de8136ff6b175319a41a787e
